### ISSUE TITLE
Panic with VersionParseError on `"^1.0.0,!=1.1.0"`

### ISSUE THREAD

**Issue by nh13** [mkniewallner/migrate-to-uv#234]
First off, thank-you so much for developing this tool, I imagine it was a lot of effort!

I am migrating from poetry to uv using this tool and I get a panic:

```console
uvx migrate-to-uv        

thread 'main' panicked at src/converters/poetry/version.rs:33:45:
called `Result::unwrap()` on an `Err` value: VersionParseError { kind: UnexpectedEnd { version: "1.0.0", remaining: ",!=1.1.0" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) nhomer@Nilss-MacBook-Pro prymer % vim src/converters/poetry/version.rs
```

in the `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = "^3.12"
pyproject_hooks= "^1.0.0,!=1.1.0"
```
