### ISSUE TITLE
Support migrating Poetry Optional dependency groups

### ISSUE THREAD

**Issue by antdking** [mkniewallner/migrate-to-uv#261]
docs ref:
https://python-poetry.org/docs/1.8/managing-dependencies/#optional-groups
https://python-poetry.org/docs/managing-dependencies/#optional-groups

Both Poetry and uv allow specifying groups of dependencies for use in dev environments that are not installed by default.

Given a config containing the following:

```toml
[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[tool.poetry.group.profiling]
optional = true

[tool.poetry.group.profiling.dependencies]
pyinstrument = "^4.4.0"
```

The expectation is that the group `test` becomes part of `tool.uv.default-groups`, and the group `docs` is not included.

expected output:

```toml
[dependency-groups]
test = [
  "pytest>=7.4.3,<8",
]
profiling = [
  "pyinstrument>=4.4.0,<5",
]

[tool.uv]
default-groups = [
    "test",
]
```
