### ISSUE TITLE
Apply package normalisation when searching for dependencies from extras

### ISSUE THREAD

**Issue by mkniewallner** [mkniewallner/migrate-to-uv#31]
When searching for dependencies referenced in `[tool.poetry.extras]`, Poetry applies [package normalisation](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization).

This can be confirmed with the following `pyproject.toml`:

```toml
[tool.poetry]
name = "foo"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python-dateutil = { version = "2.9.0.post0", optional = true }

[tool.poetry.extras]
date = ["PyThOn_DATEUTIL"]
```

and running:

```console
$ poetry build --format wheel --quiet && unzip -p dist/foo-0.0.1-py2.py3-none-any.whl | grep 'Requires-Dist'
Requires-Dist: python-dateutil (==2.9.0.post0) ; extra == "date"
```

The same normalization should be applied when searching for dependencies referenced in `[tool.poetry.extras]` during migration to `[project.optional-dependencies]`.
